services:
  app:
    image: almuko/telegram-app:latest
    container_name: telegram_app
    working_dir: /var/www
    restart: always
    env_file:
      - .env
    volumes:
      - storage_data:/var/www/storage
      - uploads_data:/var/www/public/uploads
      - public_data:/var/www/public
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: telegram_web
    restart: always
    ports:
      - "8081:80"
    volumes:
      - storage_data:/var/www/storage
      - uploads_data:/var/www/public/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - public_data:/var/www/public
    depends_on:
      - app

  db:
    image: postgres:17
    container_name: telegram_db
    restart: always
    environment:
      POSTGRES_DB: telegram
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Zxcvbnm123
    volumes:
      - telegram_pgdata:/var/lib/postgresql/data

volumes:
  storage_data:
  telegram_pgdata:
  uploads_data:
  public_data: