name: CI/CD Deploy to VPS
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22          
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-    

      - name: Install frontend deps
        run: npm install
        working-directory: .

      - name: Build frontend
        run: npm run build  
        working-directory: .

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          no-cache: true
          tags: |
            almuko/uibirzhasi-app:latest
            almuko/uibirzhasi-app:${{ github.sha }}
          build-args: |
            APP_BUILD=${{ github.sha }}
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          command_timeout: 40m
          script_stop: true
          script: |
            set -e
            cd ${{ secrets.VPS_PATH }}
            echo "APP_BUILD=${{ github.sha }}" >> .env
            docker compose pull
            docker compose up -d --force-recreate
            # 🧹 очистка старых образов (безопасно)
            docker image prune -f
